# Consistent hashing library PHP extension
# pyke@dailymotion.com - 05/2009

test: test_php test_hhvm
test_php: modules/chash.so
	php -n -c php_chash.ini -f chash_test.php

modules/chash.so: Makefile.php chash.c
	make -f Makefile.php

Makefile.php: config.m4
	phpize
	CFLAGS="-Wall -O3" ./configure
	mv Makefile Makefile.php

clean:

distclean: debclean
	make -f Makefile.php distclean
	phpize --clean

deb:
	debuild -i -us -uc -b

debclean:
	debuild clean
